---
title: "TITLE" #change title here
subtitle: "SUBTITLE" #change subtitle here
date: "XX/XX/202X" #change date here
output:
  pdf_document:
    number_sections: true
    pandoc_args:
      - --lua-filter=wordcount.lua
      - --metadata=wordcount=process
    latex_engine: pdflatex #xelatex #lualatex #pdflatex
    includes:
      in_header: styles/preamble.tex #include styling
    keep_tex:  false
  bookdown::pdf_book:
    citation_package: biblatex  #natbib #biblatex
bibliography: ["`r paste(list.files(path = 'bib', pattern = '^.+\\.bib$', full.names = TRUE), collapse='\",\"')`"]
csl: styles/my.csl #include citation styleing
lang: de #change language here
fontsize: 12pt #change font size here #max=12
urlcolor: "blue"
---

<!-- this chunk is your setup-chunk  -->

```{r setup, include=FALSE}
 knitr::opts_chunk$set(
 echo = FALSE,
 message = FALSE,
 warning = FALSE
 )

knitr::knit_hooks$set(inline = function(x) {   if(!is.numeric(x)){     x   }else{    prettyNum(round(x,2), big.mark=".")    } })

options("scipen" = 100, "digits" = 4)
```

<!-- load libraries -->

```{r}

packages <- c("tidyverse", "stargazer") # put your used packages in this vector

installed_packages <- packages %in% rownames(installed.packages())

# if the package is installed it has been loaded, if not, it has been installed and then loaded
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# library all packages from the vector packages
invisible(lapply(packages, library, character.only = TRUE))

```

<!-- automatically create a bib database for R packages -->

```{r include=FALSE}
knitr::write_bib(c(.packages(), 'knitr', 'rmarkdown'),
                 'bib/packages.bib')
```

<!-- load data -->

```{r}
data(starwars) #example dataframe
```

<!-- include title -->
\pagenumbering{gobble} <!-- disable page numbering   -->

```{r, child=c('children/000title.Rmd')}
```

\pagebreak <!-- new page -->
\pagenumbering{roman} <!-- set page numbering to roman numbers -->

<!-- include abstract -->

\setstretch{1.5} <!-- line spaceing 1.5-->
```{r, child=c('children/002abstract.Rmd')}
```

<!-- include lof, lot, toc -->

\setstretch{1}
\pagebreak
\listoffigures

\pagebreak
\listoftables

\pagebreak
\tableofcontents

\pagebreak
\afterpage{\blankpage}

<!-- comment in if you use abbreviations use like in example-->
<!--

```{r, child=c('children/001abbreviations.rmd')}
```

Some text \ac{rmd}
-->

\pagebreak
\pagenumbering{arabic} <!-- set page numbering to arabic numbers -->

<!-- include chapter / children -->

\setstretch{1.5} <!-- set line spaceing -->
```{r, child=c('children/010introduction.rmd', 'children/020literature_review.rmd', 'children/030hypotheses.rmd', 'children/040operationalization.rmd', 'children/050analysis.rmd', 'children/060conclusion.rmd')}
```

<!-- include bibliography -->

\pagebreak
# Literaturverzeichnis
<div id="refs"></div>

<!-- include apendix -->

\pagebreak
\pagenumbering{gobble}

# Anhang {-}

\thispagestyle{empty}
\pagenumbering{gobble}

```{r, child=c('children/999apendix.Rmd')}
```
