\setlength{\parindent}{0pt}
# Ehrenwörtliche Erklärung 

`r paste0(yaml$author)`

Matrikelnummer: `r paste0(yaml$matriculation_number)`

HF: `r paste0(yaml$subject)` \hspace{1em} 

NF: `r paste0(yaml$subject2)`

\vskip1cm

Hiermit bestätigen ich, dass ich die vorliegende Arbeit mit dem Titel
\vskip0.5em

\begin{center}
\textbf{`r paste0(yaml$title)`}

\textit{`r paste0(yaml$subtitle)`}
\rule{16.75cm}{0.4pt}
\end{center}
eigenständig angefertigt und keine anderen als die angegebenen Quellen und Hilfsmittel benutzt haben. Des Weiteren erklären ich, dass ich alle wörtlichen und indirekten Zitate sowie Grafiken, Tabellen und Abbildungen aus den angegebenen Quellen und Hilfsmitteln korrekt gekennzeichnet haben.

Mir ist bekannt, dass ein Verstoß gegen diese Regeln als Plagiat betrachtet wird. In diesem Fall wird die Arbeit mit "nicht ausreichend" bewertet. Im Wiederholungsfall hat dies den Ausschluss von weiteren Prüfungen - und damit von Studium zur Folge.


\vskip1cm
\rule{5cm}{0.4pt}
`r paste0(yaml$location)`, `r paste0(yaml$date)` 