# Forschungsstand 

Dieses Kapitel kann sich aus zwei Quellen speisen: Theorien und bestehende empirische Befunde. Diese Zweiteilung kann durch Unterkapitel manifestiert sein. Genauso gut können in einem gemeinsamen Kapitel zum Forschungsstand theoretische Antworten und zugehörige empirische Ergebnisse verwoben sein.

## Theorien
Die ausgewhlten Theorien geben eine erste vorläufige Antwort auf die in der Einleitung aufgeworfene Forschungsfrage. Dabei geht es in diesem Kapitel darum, die Theorie insgesamt zu präsentieren und dann daraus das, für die eigene Forschung verwendete, theoretische Modell zu verdeutlichen. Wenn die Theorie nicht zu komplex ist, kann Sie auch in Gänze empirisch untersucht werden.
Aus den Theorien heraus müssen die Mechanismen beschrieben werden, die den späteren Hypothesen zugrunde liegen. Das bedeutet, die Erwartungen an z.B. eine bestimmte Wirkung eines Sachverhalts muss begründet werden. Die Basis dieser Begründungen kann durch eigene logische Überlegungen oder durch empirische Befunde gelegt werden.

## Empirische Befunde
In einem ersten Schritt sollte hier über Studien berichtet werden, die ihren Fokus auf eine, der eigenen Forschung sehr nahe, Fragestellung haben. Danach können Studien und ihre Ergebnisse einbezogen werden, die sich mit Randaspekten der zu behandelnden Fragestellung beschäftigen. Die empirischen Befunde sollen sich an der Forschungsfrage orientieren und nicht am Forschungsfeld insgesamt. Die ausgewählten empirischen Befunde sollen sich in den Hypothesen möglichst niederschlagen.